"""Shared rendering pipeline for Chinese study-book outputs."""

from __future__ import annotations

import html
import io
import json
import os
import re
import tempfile
import uuid
import zipfile
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CACHE_DIR = ROOT / ".cache"
ARGOS_ROOT = CACHE_DIR / "argos"
OUTPUT_DIR = ROOT / "output"
HTML_OUTPUT_DIR = OUTPUT_DIR / "html"
EPUB_OUTPUT_DIR = OUTPUT_DIR / "epub"
PDF_OUTPUT_DIR = OUTPUT_DIR / "pdf"
TRANSLATION_CACHE_PATH = CACHE_DIR / "sentence_translations.json"

# Keep all Argos data inside the repo so the project is self-contained.
os.environ.setdefault("XDG_DATA_HOME", str(ARGOS_ROOT / "data"))
os.environ.setdefault("XDG_CACHE_HOME", str(ARGOS_ROOT / "cache"))
os.environ.setdefault("XDG_CONFIG_HOME", str(ARGOS_ROOT / "config"))
os.environ.setdefault("ARGOS_PACKAGES_DIR", str(ARGOS_ROOT / "packages"))
os.environ.setdefault("ARGOS_BEAM_SIZE", "1")
if (Path("/opt/homebrew/lib") / "libgobject-2.0.dylib").exists():
    os.environ.setdefault("DYLD_LIBRARY_PATH", "/opt/homebrew/lib")

try:
    import certifi  # type: ignore

    ca_bundle = certifi.where()
    os.environ.setdefault("SSL_CERT_FILE", ca_bundle)
    os.environ.setdefault("REQUESTS_CA_BUNDLE", ca_bundle)
except Exception:
    pass

from markdown import markdown as render_markdown  # noqa: E402
from pypinyin import Style, lazy_pinyin  # noqa: E402

HANZI_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
TITLE_HINT_RE = re.compile(r"[。！？!?：:；;]")
CLOSING_QUOTES = set("”’」』）》】」』）)]}")
LIST_ITEM_RE = re.compile(r"^\s*([-*+]|\d+\.)\s+")
TEXT_UNIT_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]|[A-Za-z0-9]+")
DEFAULT_CHUNK_SIZE = 5000
PDF_MONOCHROME_CSS = """
<style>
  * {
    color: #000 !important;
  }

  .pdf-ruby {
    display: inline-block;
    margin-right: 0.03em;
    text-align: center;
    vertical-align: baseline;
    line-height: 1;
  }

  .pdf-ruby .pdf-rt {
    display: block;
    font-size: 0.5em;
    line-height: 1;
  }

  .pdf-ruby .pdf-rb {
    display: block;
    line-height: 1.15;
  }
</style>
"""
RUBY_TAG_RE = re.compile(
    r'<ruby class="hz"><rb>(.*?)</rb><rt>(.*?)</rt></ruby>',
    re.DOTALL,
)


PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-Hans">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <style>
    :root {{
      --page-width: 8.5in;
      --text: #000;
      --muted: #000;
      --paper: #fffdf8;
      --rule: #d8cebf;
      --translation: #000;
      --accent: #000;
    }}

    @page {{
      size: letter portrait;
      margin: 0.55in;
    }}

    * {{
      box-sizing: border-box;
    }}

    body {{
      margin: 0;
      color: var(--text);
      background:
        radial-gradient(circle at top left, #f3ecdf 0, transparent 22rem),
        linear-gradient(180deg, #f7f1e5 0%, var(--paper) 18%, #fff 100%);
      font-family: "Times New Roman", "Noto Serif CJK SC", "Songti SC", serif;
      line-height: 1.75;
    }}

    main {{
      max-width: var(--page-width);
      margin: 0 auto;
      padding: 0.65in 0.55in 0.9in;
    }}

    h1, h2, h3, h4, h5, h6 {{
      page-break-after: avoid;
      font-weight: 600;
      line-height: 1.3;
      margin: 0 0 0.8rem;
      text-align: center;
      color: var(--accent);
    }}

    h1 {{
      font-size: 1.9rem;
      letter-spacing: 0.08em;
      margin-bottom: 1.4rem;
    }}

    .paragraph,
    .list-block {{
      margin: 0 0 1.25rem;
    }}

    .sentence {{
      page-break-inside: avoid;
      margin: 0 0 0.7rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid rgba(216, 206, 191, 0.45);
    }}

    .sentence:last-child {{
      border-bottom: 0;
      padding-bottom: 0;
    }}

    .hanzi-line,
    .english-line {{
      margin: 0;
    }}

    .hanzi-line {{
      font-size: 1.06rem;
      text-wrap: pretty;
    }}

    .english-line {{
      margin-top: 0.2rem;
      color: var(--translation);
      font-size: 0.92rem;
      line-height: 1.55;
      font-style: italic;
    }}

    ruby.hz {{
      ruby-position: over;
      margin-right: 0.03em;
    }}

    ruby.hz rt {{
      font-size: 0.5em;
      color: var(--muted);
      letter-spacing: 0.01em;
      user-select: none;
    }}

    ul, ol {{
      padding-left: 1.2rem;
    }}

    li {{
      margin-bottom: 0.8rem;
    }}

    .meta {{
      margin-top: 2rem;
      color: var(--muted);
      font-size: 0.85rem;
      text-align: center;
    }}

    @media print {{
      body {{
        background: #fff;
      }}

      main {{
        max-width: none;
        padding: 0;
      }}
    }}
  </style>
</head>
<body>
  <main>
    {body}
    <div class="meta">Generated by the local Markdown-to-study-sheet pipeline.</div>
  </main>
</body>
</html>
"""

EPUB_STYLES = """body {
  margin: 0;
  padding: 0 0.5em 1.2em;
  color: #000;
  font-family: serif;
  line-height: 1.7;
}

h1, h2, h3, h4, h5, h6 {
  text-align: center;
  line-height: 1.3;
  margin: 0.8em 0;
}

h1 {
  font-size: 1.5em;
}

.paragraph,
.list-block {
  margin: 0 0 1.1em;
}

.sentence {
  margin: 0 0 0.7em;
  padding-bottom: 0.45em;
  border-bottom: 1px solid #ddd2c2;
}

.sentence:last-child {
  border-bottom: 0;
}

.hanzi-line,
.english-line {
  margin: 0;
}

.hanzi-line {
  font-size: 1.05em;
}

.english-line {
  margin-top: 0.2em;
  color: #000;
  font-size: 0.9em;
  font-style: italic;
}

ruby.hz rt {
  font-size: 0.55em;
  color: #000;
}

li {
  margin-bottom: 0.7em;
}
"""

EPUB_CHAPTER_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-Hans">
  <head>
    <title>{title}</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="styles/book.css" />
  </head>
  <body>
    {body}
  </body>
</html>
"""

EPUB_NAV_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en">
  <head>
    <title>Table of Contents</title>
    <meta charset="utf-8" />
  </head>
  <body>
    <nav epub:type="toc" id="toc">
      <h1>Contents</h1>
      <ol>
        <li><a href="chapter.xhtml">{title}</a></li>
      </ol>
    </nav>
  </body>
</html>
"""

EPUB_CONTAINER_XML = """<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"""


@dataclass
class Block:
    kind: str
    text: str
    level: int = 0


@dataclass
class RenderChunk:
    title: str
    body: str


ChunkWriter = Callable[[Path, str, str], None]


class TranslationCache:
    def __init__(self, path: Path):
        self.path = path
        if path.exists():
            self.data = json.loads(path.read_text(encoding="utf-8"))
        else:
            self.data = {}

    def get(self, sentence: str) -> str | None:
        return self.data.get(sentence)

    def put(self, sentence: str, translation: str) -> None:
        self.data[sentence] = translation

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(self.data, ensure_ascii=False, indent=2, sort_keys=True),
            encoding="utf-8",
        )


class InlineRubyAnnotator(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        rendered_attrs = []
        for key, value in attrs:
            if value is None:
                rendered_attrs.append(key)
            else:
                rendered_attrs.append(f'{key}="{html.escape(value, quote=True)}"')
        suffix = f" {' '.join(rendered_attrs)}" if rendered_attrs else ""
        self.parts.append(f"<{tag}{suffix}>")

    def handle_endtag(self, tag: str) -> None:
        self.parts.append(f"</{tag}>")

    def handle_startendtag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        rendered_attrs = []
        for key, value in attrs:
            if value is None:
                rendered_attrs.append(key)
            else:
                rendered_attrs.append(f'{key}="{html.escape(value, quote=True)}"')
        suffix = f" {' '.join(rendered_attrs)}" if rendered_attrs else ""
        self.parts.append(f"<{tag}{suffix} />")

    def handle_data(self, data: str) -> None:
        self.parts.append(add_ruby_markup(data))

    def handle_entityref(self, name: str) -> None:
        self.parts.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        self.parts.append(f"&#{name};")

    def get_html(self) -> str:
        return "".join(self.parts)


class SentenceTranslator:
    def __init__(self):
        self._translation = None

    def _get_translation(self):
        if self._translation is not None:
            return self._translation

        import argostranslate.translate

        installed_languages = argostranslate.translate.get_installed_languages()
        from_lang = next((lang for lang in installed_languages if lang.code == "zh"), None)
        to_lang = next((lang for lang in installed_languages if lang.code == "en"), None)

        if from_lang is None or to_lang is None or from_lang.get_translation(to_lang) is None:
            raise RuntimeError(
                "Chinese→English Argos package is not installed. "
                "Run `venv/bin/python setup_translate.py` first."
            )

        self._translation = from_lang.get_translation(to_lang)
        # We split sentences ourselves, so bypass Argos sentence boundary detection
        # on the wrapped PackageTranslation objects and keep rendering offline.
        disable_argos_sbd(self._translation)
        return self._translation

    def translate(self, sentence: str) -> str:
        translation = self._get_translation().translate(sentence.strip())
        return normalize_whitespace(translation)


class PassthroughSentencizer:
    def split_sentences(self, text: str) -> list[str]:
        return [text]


def disable_argos_sbd(translation) -> None:
    if hasattr(translation, "sentencizer"):
        translation.sentencizer = PassthroughSentencizer()
    if hasattr(translation, "underlying"):
        disable_argos_sbd(translation.underlying)
    if hasattr(translation, "t1"):
        disable_argos_sbd(translation.t1)
    if hasattr(translation, "t2"):
        disable_argos_sbd(translation.t2)


def normalize_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def strip_wrapping_paragraph_tag(rendered: str) -> str:
    stripped = rendered.strip()
    if stripped.startswith("<p>") and stripped.endswith("</p>"):
        return stripped[3:-4]
    return stripped


def add_ruby_markup(text: str) -> str:
    if not text:
        return ""

    syllables = lazy_pinyin(
        text,
        style=Style.TONE,
        neutral_tone_with_five=True,
        strict=False,
        errors=lambda value: list(value),
    )

    parts: list[str] = []
    for char, syllable in zip(text, syllables):
        if char == "\n":
            parts.append("<br />")
        elif HANZI_RE.fullmatch(char):
            parts.append(
                '<ruby class="hz"><rb>{}</rb><rt>{}</rt></ruby>'.format(
                    html.escape(char),
                    html.escape(syllable),
                )
            )
        else:
            parts.append(html.escape(char))
    return "".join(parts)


def annotate_inline_html(fragment: str) -> str:
    parser = InlineRubyAnnotator()
    parser.feed(fragment)
    parser.close()
    return parser.get_html()


def render_inline(text: str) -> str:
    rendered = render_markdown(text, extensions=["extra", "nl2br"])
    return strip_wrapping_paragraph_tag(rendered)


def split_sentences(text: str) -> list[str]:
    sentences: list[str] = []
    buffer: list[str] = []
    terminators = {"。", "！", "？", "!", "?"}

    for char in text:
        buffer.append(char)
        if char not in terminators:
            continue

        sentence = "".join(buffer)
        buffer = []
        sentences.append(sentence)

    if buffer:
        tail = "".join(buffer).strip()
        if tail:
            sentences.append(tail)

    merged: list[str] = []
    for sentence in sentences:
        cleaned = sentence.strip()
        if not cleaned:
            continue
        if cleaned and all(ch in CLOSING_QUOTES for ch in cleaned):
            if merged:
                merged[-1] += cleaned
            continue
        merged.append(cleaned)

    return merged


def estimate_text_units(text: str) -> int:
    return len(TEXT_UNIT_RE.findall(text))


def split_text_for_chunks(text: str, max_units: int) -> list[str]:
    sentences = split_sentences(text)
    if not sentences:
        cleaned = text.strip()
        return [cleaned] if cleaned else []

    chunks: list[str] = []
    current: list[str] = []
    current_units = 0

    for sentence in sentences:
        sentence_units = max(estimate_text_units(sentence), 1)
        if current and current_units + sentence_units > max_units:
            chunks.append("".join(current).strip())
            current = []
            current_units = 0
        current.append(sentence)
        current_units += sentence_units

    if current:
        chunks.append("".join(current).strip())

    return [chunk for chunk in chunks if chunk]


def parse_blocks(markdown_text: str) -> list[Block]:
    lines = markdown_text.splitlines()
    blocks: list[Block] = []
    buffer: list[str] = []
    first_content_block = True

    def flush_buffer() -> None:
        nonlocal buffer, first_content_block
        if not buffer:
            return
        text = "\n".join(buffer).strip()
        buffer = []
        if not text:
            return
        if first_content_block and not TITLE_HINT_RE.search(text) and len(text) <= 60:
            blocks.append(Block(kind="heading", text=text, level=1))
        elif all(LIST_ITEM_RE.match(line) for line in text.splitlines()):
            blocks.append(Block(kind="list", text=text))
        else:
            blocks.append(Block(kind="paragraph", text=text))
        first_content_block = False

    for line in lines:
        heading_match = HEADING_RE.match(line)
        if heading_match:
            flush_buffer()
            blocks.append(
                Block(
                    kind="heading",
                    text=heading_match.group(2).strip(),
                    level=len(heading_match.group(1)),
                )
            )
            first_content_block = False
            continue
        if not line.strip():
            flush_buffer()
            continue
        buffer.append(line.rstrip())

    flush_buffer()
    return blocks


def split_blocks_for_chunks(blocks: list[Block], max_units: int) -> list[list[Block]]:
    expanded: list[tuple[Block, int]] = []
    for block in blocks:
        if block.kind == "paragraph":
            for piece in split_text_for_chunks(block.text, max_units):
                expanded.append((Block(kind="paragraph", text=piece, level=block.level), estimate_text_units(piece)))
            continue
        expanded.append((block, estimate_text_units(block.text)))

    chunks: list[list[Block]] = []
    current: list[Block] = []
    current_units = 0

    for block, block_units in expanded:
        if current and block.kind != "heading" and current_units + block_units > max_units:
            chunks.append(current)
            current = []
            current_units = 0
        current.append(block)
        if block.kind != "heading":
            current_units += block_units

    if current:
        chunks.append(current)

    return chunks


def render_sentence(sentence: str, translator: SentenceTranslator, cache: TranslationCache) -> str:
    cached = cache.get(sentence)
    if cached is None:
        cached = translator.translate(sentence)
        cache.put(sentence, cached)

    annotated = annotate_inline_html(render_inline(sentence))
    english = html.escape(cached)
    return (
        '<div class="sentence">'
        f'<p class="hanzi-line">{annotated}</p>'
        f'<p class="english-line">{english}</p>'
        "</div>"
    )


def render_paragraph(block: Block, translator: SentenceTranslator, cache: TranslationCache) -> str:
    sentences = split_sentences(block.text)
    if not sentences:
        return ""
    rendered = "".join(render_sentence(sentence, translator, cache) for sentence in sentences)
    return f'<section class="paragraph">{rendered}</section>'


def render_list(block: Block, translator: SentenceTranslator, cache: TranslationCache) -> str:
    items = []
    for line in block.text.splitlines():
        item_text = LIST_ITEM_RE.sub("", line).strip()
        if not item_text:
            continue
        items.append(f"<li>{render_paragraph(Block(kind='paragraph', text=item_text), translator, cache)}</li>")
    return f'<section class="list-block"><ul>{"".join(items)}</ul></section>'


def render_heading(block: Block) -> str:
    level = min(max(block.level or 1, 1), 6)
    annotated = annotate_inline_html(render_inline(block.text))
    return f"<h{level}>{annotated}</h{level}>"


def extract_title(blocks: list[Block]) -> str:
    for block in blocks:
        if block.kind == "heading":
            return normalize_whitespace(block.text)
    return "Printable Chinese Reader"


def render_blocks(blocks: list[Block], translator: SentenceTranslator, cache: TranslationCache) -> str:
    body_parts: list[str] = []
    for block in blocks:
        if block.kind == "heading":
            body_parts.append(render_heading(block))
        elif block.kind == "list":
            body_parts.append(render_list(block, translator, cache))
        else:
            body_parts.append(render_paragraph(block, translator, cache))
    return "\n".join(part for part in body_parts if part)


def render_document(markdown_text: str, translator: SentenceTranslator, cache: TranslationCache) -> tuple[str, str]:
    blocks = parse_blocks(markdown_text)
    title = extract_title(blocks)
    body = render_blocks(blocks, translator, cache)
    return title, body


def render_document_chunks(
    markdown_text: str,
    translator: SentenceTranslator,
    cache: TranslationCache,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
) -> list[RenderChunk]:
    blocks = parse_blocks(markdown_text)
    base_title = extract_title(blocks)
    block_chunks = split_blocks_for_chunks(blocks, chunk_size)
    total = len(block_chunks)
    rendered_chunks: list[RenderChunk] = []

    for index, chunk_blocks in enumerate(block_chunks, start=1):
        chunk_title = base_title if total == 1 else f"{base_title} Part {index}"
        rendered_chunks.append(RenderChunk(title=chunk_title, body=render_blocks(chunk_blocks, translator, cache)))

    return rendered_chunks


def prepare_document_chunks(markdown_text: str, chunk_size: int) -> tuple[str, list[list[Block]]]:
    blocks = parse_blocks(markdown_text)
    return extract_title(blocks), split_blocks_for_chunks(blocks, chunk_size)


def render_html_page(title: str, body: str) -> str:
    return PAGE_TEMPLATE.format(title=html.escape(title), body=body)


def force_monochrome_html(html_text: str) -> str:
    if "</head>" in html_text:
        return html_text.replace("</head>", f"{PDF_MONOCHROME_CSS}\n</head>", 1)
    return f"{PDF_MONOCHROME_CSS}\n{html_text}"


def make_html_pdf_compatible(html_text: str) -> str:
    def replace_ruby(match: re.Match[str]) -> str:
        rb = match.group(1)
        rt = match.group(2)
        return (
            '<span class="pdf-ruby">'
            f'<span class="pdf-rt">{rt}</span>'
            f'<span class="pdf-rb">{rb}</span>'
            "</span>"
        )

    return RUBY_TAG_RE.sub(replace_ruby, force_monochrome_html(html_text))


def pdf_footer_label(output_path: Path) -> str:
    stem = output_path.stem
    if stem.startswith("chapter_"):
        return f"Chapter {stem.removeprefix('chapter_')}"
    return stem


def add_pdf_page_numbers(input_path: Path, output_path: Path, footer_label: str) -> None:
    try:
        from pypdf import PdfReader, PdfWriter
        from reportlab.pdfgen import canvas
    except ImportError as exc:
        raise RuntimeError(
            "PDF page numbering requires pypdf and reportlab. "
            "Install them with `venv/bin/pip install pypdf reportlab`."
        ) from exc

    reader = PdfReader(str(input_path))
    writer = PdfWriter()

    for index, page in enumerate(reader.pages, start=1):
        width = float(page.mediabox.width)
        height = float(page.mediabox.height)
        packet = io.BytesIO()
        overlay = canvas.Canvas(packet, pagesize=(width, height))
        overlay.setFillColorRGB(0, 0, 0)
        overlay.setFont("Times-Roman", 9)
        footer = f"{footer_label} page {index}"
        overlay.drawCentredString(width / 2, 24, footer)
        overlay.save()

        packet.seek(0)
        overlay_page = PdfReader(packet).pages[0]
        page.merge_page(overlay_page)
        writer.add_page(page)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("wb") as output_file:
        writer.write(output_file)


def write_pdf_with_weasyprint(output_path: Path, title: str, body: str) -> None:
    from weasyprint import HTML

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_html = make_html_pdf_compatible(render_html_page(title, body))
    with tempfile.NamedTemporaryFile(
        suffix=".pdf",
        dir=output_path.parent,
        delete=False,
    ) as temp_file:
        raw_pdf_path = Path(temp_file.name)
    try:
        HTML(string=output_html, base_url=str(ROOT)).write_pdf(raw_pdf_path)
        add_pdf_page_numbers(raw_pdf_path, output_path, pdf_footer_label(output_path))
    finally:
        raw_pdf_path.unlink(missing_ok=True)


def build_epub_opf(title: str, identifier: str) -> str:
    escaped_title = html.escape(title)
    escaped_identifier = html.escape(identifier)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="bookid">{escaped_identifier}</dc:identifier>
    <dc:title>{escaped_title}</dc:title>
    <dc:language>zh-CN</dc:language>
    <meta property="dcterms:modified">2026-04-21T00:00:00Z</meta>
  </metadata>
  <manifest>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="chapter" href="chapter.xhtml" media-type="application/xhtml+xml"/>
    <item id="css" href="styles/book.css" media-type="text/css"/>
  </manifest>
  <spine>
    <itemref idref="chapter"/>
  </spine>
</package>
"""


def write_epub(output_path: Path, title: str, body: str) -> None:
    identifier = f"urn:uuid:{uuid.uuid5(uuid.NAMESPACE_URL, title)}"
    chapter_xhtml = EPUB_CHAPTER_TEMPLATE.format(
        title=html.escape(title),
        body=body,
    )
    nav_xhtml = EPUB_NAV_TEMPLATE.format(title=html.escape(title))
    content_opf = build_epub_opf(title, identifier)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_path, "w") as epub:
        epub.writestr(
            zipfile.ZipInfo("mimetype"),
            "application/epub+zip",
            compress_type=zipfile.ZIP_STORED,
        )
        epub.writestr("META-INF/container.xml", EPUB_CONTAINER_XML)
        epub.writestr("OEBPS/content.opf", content_opf)
        epub.writestr("OEBPS/nav.xhtml", nav_xhtml)
        epub.writestr("OEBPS/chapter.xhtml", chapter_xhtml)
        epub.writestr("OEBPS/styles/book.css", EPUB_STYLES)


def write_pdf(output_path: Path, title: str, body: str) -> None:
    try:
        write_pdf_with_weasyprint(output_path, title, body)
    except Exception as exc:
        raise RuntimeError(
            "PDF rendering requires WeasyPrint and its native system libraries. "
            "Install Python deps with `venv/bin/pip install weasyprint pypdf reportlab`; "
            "on macOS, install WeasyPrint's native libraries if this still fails."
        ) from exc


def build_output_paths(output_path: Path, total_chunks: int) -> list[Path]:
    if total_chunks == 1:
        return [output_path]
    return [
        output_path.with_name(f"{output_path.stem}_{index}{output_path.suffix}")
        for index in range(1, total_chunks + 1)
    ]


def ensure_translation_package() -> None:
    import argostranslate.package
    import argostranslate.translate

    installed_languages = argostranslate.translate.get_installed_languages()
    from_lang = next((lang for lang in installed_languages if lang.code == "zh"), None)
    to_lang = next((lang for lang in installed_languages if lang.code == "en"), None)
    if from_lang is not None and to_lang is not None and from_lang.get_translation(to_lang) is not None:
        return

    argostranslate.package.update_package_index()
    available_packages = argostranslate.package.get_available_packages()
    package_to_install = next(
        (
            package
            for package in available_packages
            if package.from_code == "zh" and package.to_code == "en"
        ),
        None,
    )
    if package_to_install is None:
        raise RuntimeError("No Chinese→English Argos Translate package was found.")
    download_path = package_to_install.download()
    argostranslate.package.install_from_path(download_path)


def run_setup_translate() -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    ensure_translation_package()
    print(f"Chinese→English translation package is ready in {ARGOS_ROOT}")


def log_progress(message: str) -> None:
    print(message, flush=True)


def render_chunks_to_outputs(
    input_path: Path,
    output_path: Path,
    chunk_size: int,
    *,
    output_dir: Path,
    writer: ChunkWriter,
) -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    log_progress(f"Loading {input_path}")
    cache = TranslationCache(TRANSLATION_CACHE_PATH)
    translator = SentenceTranslator()
    markdown_text = input_path.read_text(encoding="utf-8")
    base_title, block_chunks = prepare_document_chunks(markdown_text, chunk_size)
    output_paths = build_output_paths(output_path, len(block_chunks))

    log_progress(f"Prepared {len(block_chunks)} chunk(s) with chunk size {chunk_size}")
    for index, (chunk_blocks, chunk_output_path) in enumerate(zip(block_chunks, output_paths), start=1):
        chunk_title = base_title if len(block_chunks) == 1 else f"{base_title} Part {index}"
        log_progress(f"[{index}/{len(block_chunks)}] Rendering {chunk_title}")
        body = render_blocks(chunk_blocks, translator, cache)
        log_progress(f"[{index}/{len(block_chunks)}] Writing {chunk_output_path}")
        writer(chunk_output_path, chunk_title, body)
        log_progress(f"[{index}/{len(block_chunks)}] Done {chunk_output_path}")

    log_progress(f"Saving translation cache to {TRANSLATION_CACHE_PATH}")
    cache.save()
    log_progress(f"Rendered {input_path} -> {len(output_paths)} file(s)")


def write_html(output_path: Path, title: str, body: str) -> None:
    output_path.write_text(render_html_page(title, body), encoding="utf-8")


def run_render_html(input_path: Path, output_path: Path, chunk_size: int = DEFAULT_CHUNK_SIZE) -> None:
    render_chunks_to_outputs(
        input_path,
        output_path,
        chunk_size,
        output_dir=HTML_OUTPUT_DIR,
        writer=write_html,
    )


def run_render_epub(input_path: Path, output_path: Path, chunk_size: int = DEFAULT_CHUNK_SIZE) -> None:
    render_chunks_to_outputs(
        input_path,
        output_path,
        chunk_size,
        output_dir=EPUB_OUTPUT_DIR,
        writer=write_epub,
    )


def run_render_pdf(input_path: Path, output_path: Path, chunk_size: int = DEFAULT_CHUNK_SIZE) -> None:
    render_chunks_to_outputs(
        input_path,
        output_path,
        chunk_size,
        output_dir=PDF_OUTPUT_DIR,
        writer=write_pdf,
    )


def run_output_cli(
    argv: Iterable[str] | None,
    *,
    description: str,
    default_output_dir: Path,
    default_suffix: str,
    runner: Callable[[Path, Path, int], None],
) -> int:
    import argparse
    import sys

    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("input", type=Path, help="Path to the source markdown file.")
    parser.add_argument("output", type=Path, nargs="?", help=f"Target {default_suffix.upper()} path.")
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=DEFAULT_CHUNK_SIZE,
        help="Approximate text units per output chunk. Chinese characters count as one unit.",
    )
    args = parser.parse_args(argv)
    output_path = args.output or default_output_dir / f"{args.input.stem.lower()}.{default_suffix}"
    try:
        runner(args.input, output_path, args.chunk_size)
    except Exception as exc:  # pragma: no cover - CLI surface
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


def run_setup_cli(argv: Iterable[str] | None = None) -> int:
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        description="Download and install the offline Chinese-to-English Argos model into this repo."
    )
    parser.parse_args(argv)
    try:
        run_setup_translate()
    except Exception as exc:  # pragma: no cover - CLI surface
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0
