from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent
CACHE_DIR = ROOT / ".cache"
ARGOS_ROOT = CACHE_DIR / "argos"
OUTPUT_DIR = ROOT / "output"
TRANSLATION_CACHE_PATH = CACHE_DIR / "sentence_translations.json"

# Keep all Argos data inside the repo so the project is self-contained.
os.environ.setdefault("XDG_DATA_HOME", str(ARGOS_ROOT / "data"))
os.environ.setdefault("XDG_CACHE_HOME", str(ARGOS_ROOT / "cache"))
os.environ.setdefault("XDG_CONFIG_HOME", str(ARGOS_ROOT / "config"))
os.environ.setdefault("ARGOS_PACKAGES_DIR", str(ARGOS_ROOT / "packages"))
os.environ.setdefault("ARGOS_BEAM_SIZE", "1")

try:
    import certifi  # type: ignore

    ca_bundle = certifi.where()
    os.environ.setdefault("SSL_CERT_FILE", ca_bundle)
    os.environ.setdefault("REQUESTS_CA_BUNDLE", ca_bundle)
except Exception:
    pass

from markdown import markdown as render_markdown  # noqa: E402
from pypinyin import Style, lazy_pinyin  # noqa: E402

HANZI_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
TITLE_HINT_RE = re.compile(r"[。！？!?：:；;]")
CLOSING_QUOTES = set("”’」』）》】」』）)]}")
LIST_ITEM_RE = re.compile(r"^\s*([-*+]|\d+\.)\s+")


PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-Hans">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <style>
    :root {{
      --page-width: 8.5in;
      --text: #1e1a16;
      --muted: #6d6256;
      --paper: #fffdf8;
      --rule: #d8cebf;
      --translation: #2a4b6b;
      --accent: #8a4b12;
    }}

    @page {{
      size: letter portrait;
      margin: 0.55in;
    }}

    * {{
      box-sizing: border-box;
    }}

    body {{
      margin: 0;
      color: var(--text);
      background:
        radial-gradient(circle at top left, #f3ecdf 0, transparent 22rem),
        linear-gradient(180deg, #f7f1e5 0%, var(--paper) 18%, #fff 100%);
      font-family: "Times New Roman", "Noto Serif CJK SC", "Songti SC", serif;
      line-height: 1.75;
    }}

    main {{
      max-width: var(--page-width);
      margin: 0 auto;
      padding: 0.65in 0.55in 0.9in;
    }}

    h1, h2, h3, h4, h5, h6 {{
      page-break-after: avoid;
      font-weight: 600;
      line-height: 1.3;
      margin: 0 0 0.8rem;
      text-align: center;
      color: var(--accent);
    }}

    h1 {{
      font-size: 1.9rem;
      letter-spacing: 0.08em;
      margin-bottom: 1.4rem;
    }}

    .paragraph,
    .list-block {{
      margin: 0 0 1.25rem;
    }}

    .sentence {{
      page-break-inside: avoid;
      margin: 0 0 0.7rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid rgba(216, 206, 191, 0.45);
    }}

    .sentence:last-child {{
      border-bottom: 0;
      padding-bottom: 0;
    }}

    .hanzi-line,
    .english-line {{
      margin: 0;
    }}

    .hanzi-line {{
      font-size: 1.06rem;
      text-wrap: pretty;
    }}

    .english-line {{
      margin-top: 0.2rem;
      color: var(--translation);
      font-size: 0.92rem;
      line-height: 1.55;
      font-style: italic;
    }}

    ruby.hz {{
      ruby-position: over;
      margin-right: 0.03em;
    }}

    ruby.hz rt {{
      font-size: 0.5em;
      color: var(--muted);
      letter-spacing: 0.01em;
      user-select: none;
    }}

    ul, ol {{
      padding-left: 1.2rem;
    }}

    li {{
      margin-bottom: 0.8rem;
    }}

    .meta {{
      margin-top: 2rem;
      color: var(--muted);
      font-size: 0.85rem;
      text-align: center;
    }}

    @media print {{
      body {{
        background: #fff;
      }}

      main {{
        max-width: none;
        padding: 0;
      }}
    }}
  </style>
</head>
<body>
  <main>
    {body}
    <div class="meta">Generated by the local Markdown-to-study-sheet pipeline.</div>
  </main>
</body>
</html>
"""


@dataclass
class Block:
    kind: str
    text: str
    level: int = 0


class TranslationCache:
    def __init__(self, path: Path):
        self.path = path
        if path.exists():
            self.data = json.loads(path.read_text(encoding="utf-8"))
        else:
            self.data = {}

    def get(self, sentence: str) -> str | None:
        return self.data.get(sentence)

    def put(self, sentence: str, translation: str) -> None:
        self.data[sentence] = translation

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(self.data, ensure_ascii=False, indent=2, sort_keys=True),
            encoding="utf-8",
        )


class InlineRubyAnnotator(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        rendered_attrs = []
        for key, value in attrs:
            if value is None:
                rendered_attrs.append(key)
            else:
                rendered_attrs.append(f'{key}="{html.escape(value, quote=True)}"')
        suffix = f" {' '.join(rendered_attrs)}" if rendered_attrs else ""
        self.parts.append(f"<{tag}{suffix}>")

    def handle_endtag(self, tag: str) -> None:
        self.parts.append(f"</{tag}>")

    def handle_startendtag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        rendered_attrs = []
        for key, value in attrs:
            if value is None:
                rendered_attrs.append(key)
            else:
                rendered_attrs.append(f'{key}="{html.escape(value, quote=True)}"')
        suffix = f" {' '.join(rendered_attrs)}" if rendered_attrs else ""
        self.parts.append(f"<{tag}{suffix} />")

    def handle_data(self, data: str) -> None:
        self.parts.append(add_ruby_markup(data))

    def handle_entityref(self, name: str) -> None:
        self.parts.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        self.parts.append(f"&#{name};")

    def get_html(self) -> str:
        return "".join(self.parts)


class SentenceTranslator:
    def __init__(self):
        self._translation = None

    def _get_translation(self):
        if self._translation is not None:
            return self._translation

        import argostranslate.translate

        installed_languages = argostranslate.translate.get_installed_languages()
        from_lang = next((lang for lang in installed_languages if lang.code == "zh"), None)
        to_lang = next((lang for lang in installed_languages if lang.code == "en"), None)

        if from_lang is None or to_lang is None or from_lang.get_translation(to_lang) is None:
            raise RuntimeError(
                "Chinese→English Argos package is not installed. "
                "Run `venv/bin/python main.py setup-translate` first."
            )

        self._translation = from_lang.get_translation(to_lang)
        # We split sentences ourselves, so bypass Argos sentence boundary detection
        # on the wrapped PackageTranslation objects and keep rendering offline.
        disable_argos_sbd(self._translation)
        return self._translation

    def translate(self, sentence: str) -> str:
        translation = self._get_translation().translate(sentence.strip())
        return normalize_whitespace(translation)


class PassthroughSentencizer:
    def split_sentences(self, text: str) -> list[str]:
        return [text]


def disable_argos_sbd(translation) -> None:
    if hasattr(translation, "sentencizer"):
        translation.sentencizer = PassthroughSentencizer()
    if hasattr(translation, "underlying"):
        disable_argos_sbd(translation.underlying)
    if hasattr(translation, "t1"):
        disable_argos_sbd(translation.t1)
    if hasattr(translation, "t2"):
        disable_argos_sbd(translation.t2)


def normalize_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def strip_wrapping_paragraph_tag(rendered: str) -> str:
    stripped = rendered.strip()
    if stripped.startswith("<p>") and stripped.endswith("</p>"):
        return stripped[3:-4]
    return stripped


def add_ruby_markup(text: str) -> str:
    if not text:
        return ""

    syllables = lazy_pinyin(
        text,
        style=Style.TONE,
        neutral_tone_with_five=True,
        strict=False,
        errors=lambda value: list(value),
    )

    parts: list[str] = []
    for char, syllable in zip(text, syllables):
        if char == "\n":
            parts.append("<br />")
        elif HANZI_RE.fullmatch(char):
            parts.append(
                '<ruby class="hz"><rb>{}</rb><rt>{}</rt></ruby>'.format(
                    html.escape(char),
                    html.escape(syllable),
                )
            )
        else:
            parts.append(html.escape(char))
    return "".join(parts)


def annotate_inline_html(fragment: str) -> str:
    parser = InlineRubyAnnotator()
    parser.feed(fragment)
    parser.close()
    return parser.get_html()


def render_inline(text: str) -> str:
    rendered = render_markdown(text, extensions=["extra", "nl2br"])
    return strip_wrapping_paragraph_tag(rendered)


def split_sentences(text: str) -> list[str]:
    sentences: list[str] = []
    buffer: list[str] = []
    terminators = {"。", "！", "？", "!", "?"}

    for char in text:
        buffer.append(char)
        if char not in terminators:
            continue

        sentence = "".join(buffer)
        buffer = []
        sentences.append(sentence)

    if buffer:
        tail = "".join(buffer).strip()
        if tail:
            sentences.append(tail)

    merged: list[str] = []
    for sentence in sentences:
        cleaned = sentence.strip()
        if not cleaned:
            continue
        if cleaned and all(ch in CLOSING_QUOTES for ch in cleaned):
            if merged:
                merged[-1] += cleaned
            continue
        merged.append(cleaned)

    return merged


def parse_blocks(markdown_text: str) -> list[Block]:
    lines = markdown_text.splitlines()
    blocks: list[Block] = []
    buffer: list[str] = []
    first_content_block = True

    def flush_buffer() -> None:
        nonlocal buffer, first_content_block
        if not buffer:
            return
        text = "\n".join(buffer).strip()
        buffer = []
        if not text:
            return
        if first_content_block and not TITLE_HINT_RE.search(text) and len(text) <= 60:
            blocks.append(Block(kind="heading", text=text, level=1))
        elif all(LIST_ITEM_RE.match(line) for line in text.splitlines()):
            blocks.append(Block(kind="list", text=text))
        else:
            blocks.append(Block(kind="paragraph", text=text))
        first_content_block = False

    for line in lines:
        heading_match = HEADING_RE.match(line)
        if heading_match:
            flush_buffer()
            blocks.append(
                Block(
                    kind="heading",
                    text=heading_match.group(2).strip(),
                    level=len(heading_match.group(1)),
                )
            )
            first_content_block = False
            continue
        if not line.strip():
            flush_buffer()
            continue
        buffer.append(line.rstrip())

    flush_buffer()
    return blocks


def render_sentence(sentence: str, translator: SentenceTranslator, cache: TranslationCache) -> str:
    cached = cache.get(sentence)
    if cached is None:
        cached = translator.translate(sentence)
        cache.put(sentence, cached)

    annotated = annotate_inline_html(render_inline(sentence))
    english = html.escape(cached)
    return (
        '<div class="sentence">'
        f'<p class="hanzi-line">{annotated}</p>'
        f'<p class="english-line">{english}</p>'
        "</div>"
    )


def render_paragraph(block: Block, translator: SentenceTranslator, cache: TranslationCache) -> str:
    sentences = split_sentences(block.text)
    if not sentences:
        return ""
    rendered = "".join(render_sentence(sentence, translator, cache) for sentence in sentences)
    return f'<section class="paragraph">{rendered}</section>'


def render_list(block: Block, translator: SentenceTranslator, cache: TranslationCache) -> str:
    items = []
    for line in block.text.splitlines():
        item_text = LIST_ITEM_RE.sub("", line).strip()
        if not item_text:
            continue
        items.append(f"<li>{render_paragraph(Block(kind='paragraph', text=item_text), translator, cache)}</li>")
    return f'<section class="list-block"><ul>{"".join(items)}</ul></section>'


def render_heading(block: Block) -> str:
    level = min(max(block.level or 1, 1), 6)
    annotated = annotate_inline_html(render_inline(block.text))
    return f"<h{level}>{annotated}</h{level}>"


def render_document(markdown_text: str, translator: SentenceTranslator, cache: TranslationCache) -> tuple[str, str]:
    body_parts: list[str] = []
    title = "Printable Chinese Reader"
    for block in parse_blocks(markdown_text):
        if block.kind == "heading":
            if title == "Printable Chinese Reader":
                title = normalize_whitespace(block.text)
            body_parts.append(render_heading(block))
        elif block.kind == "list":
            body_parts.append(render_list(block, translator, cache))
        else:
            body_parts.append(render_paragraph(block, translator, cache))
    return title, "\n".join(part for part in body_parts if part)


def ensure_translation_package() -> None:
    import argostranslate.package
    import argostranslate.translate

    installed_languages = argostranslate.translate.get_installed_languages()
    from_lang = next((lang for lang in installed_languages if lang.code == "zh"), None)
    to_lang = next((lang for lang in installed_languages if lang.code == "en"), None)
    if from_lang is not None and to_lang is not None and from_lang.get_translation(to_lang) is not None:
        return

    argostranslate.package.update_package_index()
    available_packages = argostranslate.package.get_available_packages()
    package_to_install = next(
        (
            package
            for package in available_packages
            if package.from_code == "zh" and package.to_code == "en"
        ),
        None,
    )
    if package_to_install is None:
        raise RuntimeError("No Chinese→English Argos Translate package was found.")
    download_path = package_to_install.download()
    argostranslate.package.install_from_path(download_path)


def run_setup_translate() -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    ensure_translation_package()
    print(f"Chinese→English translation package is ready in {ARGOS_ROOT}")


def run_render(input_path: Path, output_path: Path) -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    cache = TranslationCache(TRANSLATION_CACHE_PATH)
    translator = SentenceTranslator()
    markdown_text = input_path.read_text(encoding="utf-8")
    title, body = render_document(markdown_text, translator, cache)
    output_html = PAGE_TEMPLATE.format(title=html.escape(title), body=body)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output_html, encoding="utf-8")
    cache.save()
    print(f"Rendered {input_path} -> {output_path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render a Chinese markdown chapter into print-friendly HTML with pinyin and English."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    setup_parser = subparsers.add_parser(
        "setup-translate",
        help="Download and install the offline Chinese→English Argos model into this repo.",
    )
    setup_parser.set_defaults(func=lambda args: run_setup_translate())

    render_parser = subparsers.add_parser(
        "render",
        help="Convert a markdown chapter into HTML with pinyin and English translation.",
    )
    render_parser.add_argument("input", type=Path, help="Path to the source markdown file.")
    render_parser.add_argument("output", type=Path, nargs="?", help="Target HTML path.")
    render_parser.set_defaults(
        func=lambda args: run_render(
            args.input,
            args.output
            or OUTPUT_DIR / f"{args.input.stem}.html",
        )
    )
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
    except Exception as exc:  # pragma: no cover - CLI surface
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
